name: button_collection
description: This project will have variant kind of button
version: 0.0.2
homepage: https://github.com/sivhong-deab/rounded_button

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
